### ISSUE TITLE
Can't install HCYoutubeParser into a tvOS app via cocoapods

### ISSUE THREAD

**Issue by bfanger** [hellozimi/HCYoutubeParser#56]
$ pod install
> [!] The platform of the target `my-app` (tvOS 9.0) is not compatible with `HCYoutubeParser (0.0.2)`, which does not support `tvos`.

**Comment by hellozimi** [comment]
This should be fixed by commit d1666fc75689c95aa4ecd2305f6517964e4fbf15. I will submit new version to cocoapods soon.

**Comment by hellozimi** [comment]
I have now published a new version on cocoapods (0.0.4) which build for ios 7-9 and has support for tvOS. Happy coding. Let me know if you have any trouble.

**Comment by bfanger** [comment]
Works like a charm and the deprecation warnings are also gone. Thanks!

**Comment by sarbogast** [comment]
Can you give any more detail about how to do the integration? I just added the Pod to my Podfile, created a bridging header to #import the header so that it is accessible to Swift, but the compiler keeps telling me that:

Target 'Pods-TVoxx' of project 'Pods' was rejected as an implicit dependency for 'Pods_TVoxx.framework' because it doesn't contain platform 'appletvsimulator' in its SUPPORTED_PLATFORMS 'iphonesimulator, iphoneos'

Am I doing something wrong or missing something?

**Comment by bfanger** [comment]
No bridging header needed when you install it as pod, just `import HCYoutubeParser` in the swift file where you want to use the lib.

**Comment by sarbogast** [comment]
I removed my bridging header and tried to import HCYoutubeParser directly, but I'm getting these build errors:

Target 'Pods-TVoxx' of project 'Pods' was rejected as an implicit dependency for 'Pods_TVoxx.framework' because it doesn't contain platform 'appletvsimulator' in its SUPPORTED_PLATFORMS 'iphonesimulator, iphoneos'

FirstViewController.swift:10:8: No such module 'HCYoutubeParser'

**Comment by sarbogast** [comment]
FYI, here is my Podfile:

    platform :tvos, '9.0'
    use_frameworks!

    target 'TVoxx' do
      pod 'HCYoutubeParser', '~> 0.0'
    end

**Comment by sarbogast** [comment]
Sorry, I just noticed I forgot to run pod install again after changing platform in my Podfile from :ios to :tvos. Now it works.
